# Generated by Django 5.0.6 on 2024-05-14 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diagnostic',
            new_name='CatalogItem',
        ),
        migrations.AlterModelOptions(
            name='catalogitem',
            options={'ordering': ('pk',), 'verbose_name': 'Catalog item', 'verbose_name_plural': 'Catalog items'},
        ),
        migrations.DeleteModel(
            name='Procedure',
        ),
    ]
